In [1]:
import pandas as pd
t_plus_0 = pd.read_csv("./dataset_cleaned/t_plus_0.csv")
t_plus_6 = pd.read_csv("./dataset_cleaned/t_plus_6.csv")
t_plus_12 = pd.read_csv("./dataset_cleaned/t_plus_12.csv")
t_plus_24 = pd.read_csv("./dataset_cleaned/t_plus_24.csv")

display(t_plus_0)
display(t_plus_6)
display(t_plus_12)
display(t_plus_24)

visit_id  patient_id  visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0         55_0          55            0     10.0      6.0     15.0      0.0   
1         55_6          55            6      8.0     10.0     34.0      0.0   
2        55_12          55           12     10.0     10.0     41.0      0.0   
3        55_36          55           36     17.0     18.0     51.0      0.0   
4        942_6         942            6      8.0      2.0     21.0      0.0   
...        ...         ...          ...      ...      ...      ...      ...   
1063  64674_84       64674           84     11.0     15.0     45.0      4.0   
1064   65043_0       65043            0      2.0      6.0     16.0      0.0   
1065  65043_12       65043           12      4.0      7.0     14.0      0.0   
1066  65043_24       65043           24      4.0      8.0      0.0      0.0   
1067  65043_48       65043           48      7.0      6.0     13.0      0.0   

      upd23b_No  upd23b_Off  upd23b_On  ...  SSNTYTLTDVRR  \
0             1           0          0  ...      1.301037   
1             1           0          0  ...      1.750881   
2             0           0          1  ...      1.772500   
3             0           0          1  ...      2.879139   
4             1           0          0  ...     -0.657917   
...         ...         ...        ...  ...           ...   
1063          0           1          0  ...     -1.109100   
1064          1           0          0  ...      0.902720   
1065          0           1          0  ...      0.346849   
1066          1           0          0  ...      0.381411   
1067          0           1          0  ...     -0.202263   

      SRYPVC(UniMod_4)GSDGTTYPSGC(UniMod_4)QLR  LVWEEAMSR  LIADLGSTSITNLGFR  \
0                                     1.158437   0.116022          0.723859   
1                                     1.235409  -0.008089          0.456869   
2                                     0.946098   0.640441          1.307714   
3                                     1.600854   0.687493         -2.056185   
4                                     0.081967  -0.148444          0.066178   
...                                        ...        ...               ...   
1063                                 -0.072258  -1.728858         -0.581578   
1064                                  0.465699   2.841244          0.516997   
1065                                  0.546721   2.535311          0.668563   
1066                                 -0.012970   3.164386          0.892966   
1067                                 -0.115604   1.577637          0.862469   

      VFNTPEGVPSAPSSLK  GLVSWGNIPC(UniMod_4)GSK  HVEPGEPLAPSPQEPQAVGR  \
0             0.691829                 0.579532              1.323420   
1             0.384896                 0.312527              1.015371   
2             1.105815                 1.258571              0.766994   
3             0.613397                 1.439112              1.251718   
4            -0.216925                -1.022215             -0.871726   
...                ...                      ...                   ...   
1063         -1.614549                -1.585943             -0.977723   
1064          1.438126                 3.667806              2.022174   
1065          1.137948                 2.128096              1.387992   
1066          1.429332                 3.015361              0.700659   
1067          1.005437                 1.686837              0.878042   

      VHKEDDGVPVIC(UniMod_4)QVEHPAVTGNLQTQR  NPDSSTTGPWC(UniMod_4)YTTDPTVR  \
0                                  0.885020                       0.197075   
1                                  1.023829                      -0.548121   
2                                  0.802325                       0.332477   
3                                  0.273896                       0.357947   
4                                 -0.297448                       1.855541   
...                           

visit_id  patient_id  visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0        55_6          55            6      8.0     10.0     34.0      0.0   
1       55_12          55           12     10.0     10.0     41.0      0.0   
2      942_12         942           12      5.0      2.0     25.0      0.0   
3      4161_6        4161            6      1.0      2.0      0.0      0.0   
4     4161_12        4161           12      6.0      3.0     11.0      0.0   
..        ...         ...          ...      ...      ...      ...      ...   
132  62792_12       62792           12      0.0      2.0      6.0      0.0   
133   64669_6       64669            6     17.0     20.0     33.0      0.0   
134  64669_12       64669           12     12.0      9.0     17.0      0.0   
135   64674_6       64674            6     11.0      7.0     20.0      0.0   
136  64674_12       64674           12      9.0      9.0     18.0      0.0   

     upd23b_No  upd23b_Off  upd23b_On  ...  SSNTYTLTDVRR  \
0          1.0         0.0        0.0  ...      1.301037   
1          1.0         0.0        0.0  ...      1.750881   
2          1.0         0.0        0.0  ...     -0.657917   
3          1.0         0.0        0.0  ...      1.026397   
4          1.0         0.0        0.0  ...      0.283204   
..         ...         ...        ...  ...           ...   
132        1.0         0.0        0.0  ...      0.035661   
133        1.0         0.0        0.0  ...     -0.082721   
134        1.0         0.0        0.0  ...     -0.534167   
135        1.0         0.0        0.0  ...     -0.868948   
136        1.0         0.0        0.0  ...     -1.023722   

     SRYPVC(UniMod_4)GSDGTTYPSGC(UniMod_4)QLR  LVWEEAMSR  LIADLGSTSITNLGFR  \
0                                    1.158437   0.116022          0.723859   
1                                    1.235409  -0.008089          0.456869   
2                                    0.081967  -0.148444          0.066178   
3                                    2.026552  -1.148736          0.084683   
4                                    1.658710  -1.054287         -0.369798   
..                                        ...        ...               ...   
132                                  0.686031   1.321923          0.196853   
133                                  0.464104  -0.206126         -0.431789   
134                                 -0.536471  -0.655861         -0.280563   
135                                  0.089748  -0.973791         -0.968584   
136                                 -0.263632  -1.004206         -0.521052   

     VFNTPEGVPSAPSSLK  GLVSWGNIPC(UniMod_4)GSK  HVEPGEPLAPSPQEPQAVGR  \
0            0.691829                 0.579532              1.323420   
1            0.384896                 0.312527              1.015371   
2           -0.216925                -1.022215             -0.871726   
3           -0.279423                 0.221212              2.183476   
4           -0.929867                 0.040290              1.182956   
..                ...                      ...                   ...   
132          1.326643                 0.719700              1.351389   
133          0.242145                 0.053089              0.012052   
134         -0.336370                -0.421807             -0.597111   
135         -0.205741                -0.568395             -0.504843   
136         -0.552433                -1.023342             -1.231195   

     VHKEDDGVPVIC(UniMod_4)QVEHPAVTGNLQTQR  NPDSSTTGPWC(UniMod_4)YTTDPTVR  \
0                                 0.885020                       0.197075   
1                                 1.023829                      -0.548121   
2                                -0.297448                       1.855541   
3                                 1.801356                      -1.110456   
4                                 0.248527                      -0.511032   
..                                     ...                            ...   
132   

visit_id  patient_id  visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0       55_12          55           12     10.0     10.0     41.0      0.0   
1      942_24         942           24      2.0      3.0     23.0      0.0   
2     1517_36        1517           36     20.0     17.0     31.0      8.0   
3     1923_36        1923           36      3.0      0.0      1.0      0.0   
4     2660_12        2660           12      0.0      0.0      1.0      0.0   
..        ...         ...          ...      ...      ...      ...      ...   
538  64669_60       64669           60     15.0     15.0     38.0      0.0   
539  64674_12       64674           12      9.0      9.0     18.0      0.0   
540  64674_24       64674           24     12.0     12.0     26.0      0.0   
541  65043_12       65043           12      4.0      7.0     14.0      0.0   
542  65043_24       65043           24      4.0      8.0      0.0      0.0   

     upd23b_No  upd23b_Off  upd23b_On  ...  SSNTYTLTDVRR  \
0          1.0         0.0        0.0  ...      1.301037   
1          1.0         0.0        0.0  ...     -0.440893   
2          0.0         0.0        1.0  ...     -0.511109   
3          1.0         0.0        0.0  ...      1.292719   
4          1.0         0.0        0.0  ...     -0.219868   
..         ...         ...        ...  ...           ...   
538        0.0         1.0        0.0  ...     -0.609212   
539        1.0         0.0        0.0  ...     -0.868948   
540        1.0         0.0        0.0  ...     -1.375791   
541        1.0         0.0        0.0  ...      0.902720   
542        0.0         1.0        0.0  ...      0.346849   

     SRYPVC(UniMod_4)GSDGTTYPSGC(UniMod_4)QLR  LVWEEAMSR  LIADLGSTSITNLGFR  \
0                                    1.158437   0.116022          0.723859   
1                                    0.259129  -0.900650         -0.317224   
2                                   -1.086041  -0.973527          0.201046   
3                                    0.820974   0.336202         -0.160437   
4                                   -0.517581   0.821191          1.745575   
..                                        ...        ...               ...   
538                                  0.062738  -0.005459          0.084627   
539                                  0.089748  -0.973791         -0.968584   
540                                 -0.474537  -0.950505         -0.912664   
541                                  0.465699   2.841244          0.516997   
542                                  0.546721   2.535311          0.668563   

     VFNTPEGVPSAPSSLK  GLVSWGNIPC(UniMod_4)GSK  HVEPGEPLAPSPQEPQAVGR  \
0            0.691829                 0.579532              1.323420   
1           -0.425978                -0.915991             -1.285500   
2           -0.391624                -0.037933             -0.956482   
3            0.899386                 1.799476              2.537861   
4            0.830981                 0.964386              0.715814   
..                ...                      ...                   ...   
538          0.015657                -0.144285             -0.491452   
539         -0.205741                -0.568395             -0.504843   
540         -1.106472                -1.304076             -1.411299   
541          1.438126                 3.667806              2.022174   
542          1.137948                 2.128096              1.387992   

     VHKEDDGVPVIC(UniMod_4)QVEHPAVTGNLQTQR  NPDSSTTGPWC(UniMod_4)YTTDPTVR  \
0                                 0.885020                       0.197075   
1                                -0.854246                      -1.815933   
2                                -0.481995                      -0.722088   
3                                 2.621701                       0.061395   
4                                 0.433209                      -0.035245   
..                                     ...                            ...   
538   

visit_id  patient_id  visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0       55_36          55           36     17.0     18.0     51.0      0.0   
1      942_48         942           48      2.0      6.0     35.0      0.0   
2     1517_24        1517           24     19.0     11.0     28.0      3.0   
3     1517_60        1517           60     19.0     18.0     39.0     10.0   
4     1923_24        1923           24      2.0      0.0      1.0      0.0   
..        ...         ...          ...      ...      ...      ...      ...   
430  63889_60       63889           60      6.0      5.0     28.0      2.0   
431  64674_24       64674           24     12.0     12.0     26.0      0.0   
432  64674_48       64674           48     11.0     17.0     46.0      1.0   
433  65043_24       65043           24      4.0      8.0      0.0      0.0   
434  65043_48       65043           48      7.0      6.0     13.0      0.0   

     upd23b_No  upd23b_Off  upd23b_On  ...  SSNTYTLTDVRR  \
0          0.0         0.0        1.0  ...      1.772500   
1          1.0         0.0        0.0  ...     -0.375212   
2          0.0         0.0        1.0  ...     -0.026527   
3          0.0         0.0        1.0  ...      0.408586   
4          1.0         0.0        0.0  ...      1.817782   
..         ...         ...        ...  ...           ...   
430        0.0         1.0        0.0  ...     -1.116631   
431        1.0         0.0        0.0  ...     -0.868948   
432        1.0         0.0        0.0  ...     -1.013315   
433        1.0         0.0        0.0  ...      0.902720   
434        1.0         0.0        0.0  ...      0.381411   

     SRYPVC(UniMod_4)GSDGTTYPSGC(UniMod_4)QLR  LVWEEAMSR  LIADLGSTSITNLGFR  \
0                                    0.946098   0.640441          1.307714   
1                                    0.009716  -0.814511         -0.094633   
2                                    0.041232  -0.775574         -0.526301   
3                                    0.293066  -0.632017          0.515091   
4                                    1.116610   1.032949          0.667383   
..                                        ...        ...               ...   
430                                  1.024211   0.358580         -1.257845   
431                                  0.089748  -0.973791         -0.968584   
432                                  0.073598  -1.111536         -0.349692   
433                                  0.465699   2.841244          0.516997   
434                                 -0.012970   3.164386          0.892966   

     VFNTPEGVPSAPSSLK  GLVSWGNIPC(UniMod_4)GSK  HVEPGEPLAPSPQEPQAVGR  \
0            1.105815                 1.258571              0.766994   
1           -0.809281                -0.999214             -1.390454   
2           -0.604192                 0.039483             -0.760134   
3            0.436479                 0.075820             -0.340830   
4            1.389507                 2.581604              2.722331   
..                ...                      ...                   ...   
430         -0.198642                 0.514732             -1.008914   
431         -0.205741                -0.568395             -0.504843   
432         -0.473020                -1.051091             -0.820252   
433          1.438126                 3.667806              2.022174   
434          1.429332                 3.015361              0.700659   

     VHKEDDGVPVIC(UniMod_4)QVEHPAVTGNLQTQR  NPDSSTTGPWC(UniMod_4)YTTDPTVR  \
0                                 0.802325                       0.332477   
1                                -0.889770                      -1.384989   
2                                -1.422229                      -0.951212   
3                                -0.275586                      -0.693262   
4                                 2.210414                       0.220370   
..                                     ...                            ...   
430   

In [2]:
import pandas as pd

# List of file paths
file_paths = [
    'dataset_cleaned/t_plus_0.csv',
    'dataset_cleaned/t_plus_6.csv',
    'dataset_cleaned/t_plus_12.csv',
    'dataset_cleaned/t_plus_24.csv'
]

# Initialize an empty list to store DataFrames
data_frames = []

# Load and validate each CSV file
for file in file_paths:
    try:
        df = pd.read_csv(file)
        if df.empty:
            print(f"Warning: {file} is empty.")
        else:
            data_frames.append(df)
    except Exception as e:
        print(f"Error reading {file}: {e}")

# Combine all data into a single DataFrame
if data_frames:
    data = pd.concat(data_frames, ignore_index=True)

    # Print summary
    print(f"Data combined successfully! Shape: {data.shape}")
    print("First few rows:")
    print(data.head())
else:
    print("No valid data to combine.")


Data combined successfully! Shape: (2183, 139)
First few rows:
  visit_id  patient_id  visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0     55_0          55            0     10.0      6.0     15.0      0.0   
1     55_6          55            6      8.0     10.0     34.0      0.0   
2    55_12          55           12     10.0     10.0     41.0      0.0   
3    55_36          55           36     17.0     18.0     51.0      0.0   
4    942_6         942            6      8.0      2.0     21.0      0.0   

   upd23b_No  upd23b_Off  upd23b_On  ...  SSNTYTLTDVRR  \
0        1.0         0.0        0.0  ...      1.301037   
1        1.0         0.0        0.0  ...      1.750881   
2        0.0         0.0        1.0  ...      1.772500   
3        0.0         0.0        1.0  ...      2.879139   
4        1.0         0.0        0.0  ...     -0.657917   

   SRYPVC(UniMod_4)GSDGTTYPSGC(UniMod_4)QLR  LVWEEAMSR  LIADLGSTSITNLGFR  \
0                                  1.158437   0.116022       

In [3]:
# Define the target columns for UPDRS scores
updrs_columns = ['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']

# Define features (X) as all columns starting from the 11th column onward
X = data.iloc[:, 10:]  # This selects all columns from the 11th onward (0-based indexing)
y = data[updrs_columns]  # Target columns for UPDRS scores

# Check the shapes of X and y to confirm
print("Features shape:", X.shape)
print("Target shape:", y.shape)

X.head()




Features shape: (2183, 129)
Target shape: (2183, 4)


O00533    O94919    P01009    P01019    P01857    P01860    P02787  \
0  0.955709  1.672592  0.673773  0.835048 -0.798331  0.662169 -0.008787   
1  0.519166  0.917390  0.316772  0.390570 -0.804952  0.748530  0.191380   
2  1.309572  1.434594  0.282128  0.970616 -0.581383  0.359386  0.777438   
3  1.047338  1.356891  0.489235  1.527063 -0.714968  0.579983  0.447418   
4 -0.469587 -1.348507  0.427646 -0.678802 -0.743735  0.631506  0.144841   

     P04156    P04433    P05060  ...  SSNTYTLTDVRR  \
0  0.920379  0.212353 -0.341612  ...      1.301037   
1  1.141995 -0.207259 -0.244401  ...      1.750881   
2  1.155998 -0.017307  0.014345  ...      1.772500   
3  0.737451 -1.084197 -0.931780  ...      2.879139   
4  0.043632  0.116619  0.128702  ...     -0.657917   

   SRYPVC(UniMod_4)GSDGTTYPSGC(UniMod_4)QLR  LVWEEAMSR  LIADLGSTSITNLGFR  \
0                                  1.158437   0.116022          0.723859   
1                                  1.235409  -0.008089          0.456869   
2                                  0.946098   0.640441          1.307714   
3                                  1.600854   0.687493         -2.056185   
4                                  0.081967  -0.148444          0.066178   

   VFNTPEGVPSAPSSLK  GLVSWGNIPC(UniMod_4)GSK  HVEPGEPLAPSPQEPQAVGR  \
0          0.691829                 0.579532              1.323420   
1          0.384896                 0.312527              1.015371   
2          1.105815                 1.258571              0.766994   
3          0.613397                 1.439112              1.251718   
4         -0.216925                -1.022215             -0.871726   

   VHKEDDGVPVIC(UniMod_4)QVEHPAVTGNLQTQR  NPDSSTTGPWC(UniMod_4)YTTDPTVR  \
0                               0.885020                       0.197075   
1                               1.023829                      -0.548121   
2                               0.802325                       0.332477   
3                               0.273896                       0.357947   
4                              -0.297448                       1.855541   

    QALPQVR  
0  1.046352  
1  0.751295  
2  1.795828  
3  0.088250  
4 -0.523902  

[5 rows x 129 columns]

 Train and evaluate a Multi-Output Linear Regression model to predict UPDRS scores using K-Fold Cross-Validation.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Load datasets with full file paths
files = [
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_0.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_6.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_12.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_24.csv'
]
dataframes = [pd.read_csv(file) for file in files]
data = pd.concat(dataframes, ignore_index=True)

# Define features (X) and targets (y)
X = data.iloc[:, 10:]  # Features starting from column 10
y = data[['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']]  # Targets

# Initialize Multi-Output Linear Regression
lr = LinearRegression()
multi_output_lr = MultiOutputRegressor(lr)

# Function to perform K-Fold Cross-Validation
def perform_kfold_cv_separate(X, y, k):
    kf = KFold(n_splits=k, shuffle=True, random_state=42)
    results = {col: {"r2": [], "mse": []} for col in y.columns}  # Initialize results

    for train_index, test_index in kf.split(X):
        X_train_cv, X_test_cv = X.iloc[train_index], X.iloc[test_index]
        y_train_cv, y_test_cv = y.iloc[train_index], y.iloc[test_index]

        multi_output_lr.fit(X_train_cv, y_train_cv)
        y_pred_cv = multi_output_lr.predict(X_test_cv)

        # Calculate metrics for each target separately
        for i, col in enumerate(y.columns):
            cv_r2 = r2_score(y_test_cv[col], y_pred_cv[:, i])
            cv_mse = mean_squared_error(y_test_cv[col], y_pred_cv[:, i])
            results[col]["r2"].append(cv_r2)
            results[col]["mse"].append(cv_mse)

    # Print results for each target
    print(f"\nK-Fold Cross-Validation with {k} Folds:")
    for col in y.columns:
        print(f"\nTarget: {col}")
        print(f"Average R2 Score: {np.mean(results[col]['r2']):.4f}")
        print(f"Average Mean Squared Error: {np.mean(results[col]['mse']):.4f}")
        print(f"R2 Scores for Each Fold: {results[col]['r2']}")
        print(f"MSE Scores for Each Fold: {results[col]['mse']}")

# Perform 5-Fold Cross-Validation
perform_kfold_cv_separate(X, y, k=5)

# Perform 10-Fold Cross-Validation
perform_kfold_cv_separate(X, y, k=10)




K-Fold Cross-Validation with 5 Folds:

Target: updrs_1
Average R2 Score: 0.1351
Average Mean Squared Error: 24.5835
R2 Scores for Each Fold: [0.11178707188690129, 0.06298407028496023, 0.12767548542189822, 0.18625643687906346, 0.18674211483286451]
MSE Scores for Each Fold: [np.float64(22.71837036473004), np.float64(23.33550371104984), np.float64(27.735122370294626), np.float64(25.169237033164418), np.float64(23.959346678273644)]

Target: updrs_2
Average R2 Score: 0.2013
Average Mean Squared Error: 28.0866
R2 Scores for Each Fold: [0.2274768955133768, 0.14450087897095054, 0.15847057729279002, 0.24303097223855263, 0.23308344311053897]
MSE Scores for Each Fold: [np.float64(25.231625863959145), np.float64(25.427984305375308), np.float64(33.56202776884214), np.float64(30.25567725044015), np.float64(25.95572557276794)]

Target: updrs_3
Average R2 Score: 0.2316
Average Mean Squared Error: 178.3215
R2 Scores for Each Fold: [0.20576411781545612, 0.2475636279469523, 0.20178672537348263, 0.257478

Train, evaluate, save, and load a Multi-Output Linear Regression model to predict UPDRS scores.

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pickle  # Library to save and load models

# Load datasets with full file paths
files = [
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_0.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_6.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_12.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_24.csv'
]
dataframes = [pd.read_csv(file) for file in files]
data = pd.concat(dataframes, ignore_index=True)

# Define features (X) and targets (y)
X = data.iloc[:, 10:]  # Features starting from column 10
y = data[['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']]  # Targets

# Split data into training and testing sets for final model saving
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Multi-Output Linear Regression
lr = LinearRegression()
multi_output_lr = MultiOutputRegressor(lr)

# Train the final model on the training set
multi_output_lr.fit(X_train, y_train)

# Save the trained model and feature names to a file using pickle
model_filename = "linear_regression_model_with_features.pkl"
with open(model_filename, 'wb') as file:
    pickle.dump((multi_output_lr, X_train.columns.tolist()), file)
print(f"Model and feature names saved to {model_filename}")

# Evaluate the model on the test set
y_pred = multi_output_lr.predict(X_test)
r2_scores = [r2_score(y_test[col], y_pred[:, i]) for i, col in enumerate(y.columns)]
mse_scores = [mean_squared_error(y_test[col], y_pred[:, i]) for i, col in enumerate(y.columns)]

print("\nEvaluation on Test Set:")
for i, col in enumerate(y.columns):
    print(f"Target: {col}")
    print(f"R2 Score: {r2_scores[i]:.4f}")
    print(f"Mean Squared Error: {mse_scores[i]:.4f}")

# Load the saved model and feature names for future predictions
with open(model_filename, 'rb') as file:
    loaded_model, feature_names = pickle.load(file)
print("\nLoaded the saved model and feature names successfully!")

# Make predictions on new data (example with test data)
# Ensure input features align with the feature names
aligned_test_data = X_test.reindex(columns=feature_names, fill_value=0)
new_predictions = loaded_model.predict(aligned_test_data)

print("\nPredictions on Test Data:")
print(new_predictions)


Model and feature names saved to linear_regression_model_with_features.pkl

Evaluation on Test Set:
Target: updrs_1
R2 Score: 0.1116
Mean Squared Error: 22.7226
Target: updrs_2
R2 Score: 0.2275
Mean Squared Error: 25.2323
Target: updrs_3
R2 Score: 0.2058
Mean Squared Error: 173.6221
Target: updrs_4
R2 Score: 0.1596
Mean Squared Error: 3.7943

Loaded the saved model and feature names successfully!

Predictions on Test Data:
[[15.73365499  9.1134381  27.32491562  2.58378626]
 [ 5.35696889  5.39310119 15.14516709  0.7179339 ]
 [ 6.66732503  5.94252441 20.02346298  0.96539713]
 ...
 [ 5.29993917  5.27579162 25.35079453  1.50968958]
 [10.65327932  5.7810559  15.74158737  2.18766809]
 [ 3.23182393  4.48105285 21.97115585  0.81909204]]


Train and evaluate a Multi-Output Random Forest Regressor to predict UPDRS scores using K-Fold Cross-Validation.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Load datasets with full file paths
files = [
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_0.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_6.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_12.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_24.csv'
]
dataframes = [pd.read_csv(file) for file in files]

# Combine datasets (optional, depending on your workflow)
data = pd.concat(dataframes, ignore_index=True)

# Define features (X) and targets (y)
X = data.iloc[:, 10:]  # Features starting from column 10
y = data[['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']]  # Targets

# Initialize Multi-Output Random Forest Regressor
rf = RandomForestRegressor(random_state=42, n_estimators=100)
multi_output_rf = MultiOutputRegressor(rf)

# Function to perform K-Fold Cross-Validation
def perform_kfold_cv_rf_separate(X, y, k):
    kf = KFold(n_splits=k, shuffle=True, random_state=42)
    results = {col: {"r2": [], "mse": []} for col in y.columns}  # Initialize results for each UPDRS target

    for train_index, test_index in kf.split(X):
        X_train_cv, X_test_cv = X.iloc[train_index], X.iloc[test_index]
        y_train_cv, y_test_cv = y.iloc[train_index], y.iloc[test_index]

        # Train the Multi-Output Random Forest model
        multi_output_rf.fit(X_train_cv, y_train_cv)
        y_pred_cv = multi_output_rf.predict(X_test_cv)

        # Calculate metrics for each target separately
        for i, col in enumerate(y.columns):
            r2 = r2_score(y_test_cv[col], y_pred_cv[:, i])
            mse = mean_squared_error(y_test_cv[col], y_pred_cv[:, i])
            results[col]["r2"].append(r2)
            results[col]["mse"].append(mse)

    # Print results for each target
    print(f"\nK-Fold Cross-Validation with {k} Folds (Random Forest):")
    for col in y.columns:
        print(f"\nTarget: {col}")
        print(f"Average R2 Score: {np.mean(results[col]['r2']):.4f}")
        print(f"Average Mean Squared Error: {np.mean(results[col]['mse']):.4f}")
        print(f"R2 Scores for Each Fold: {results[col]['r2']}")
        print(f"MSE Scores for Each Fold: {results[col]['mse']}")

# Perform 5-Fold Cross-Validation
perform_kfold_cv_rf_separate(X, y, k=5)

# Perform 10-Fold Cross-Validation
perform_kfold_cv_rf_separate(X, y, k=10)


K-Fold Cross-Validation with 5 Folds (Random Forest):

Target: updrs_1
Average R2 Score: 0.4682
Average Mean Squared Error: 15.1548
R2 Scores for Each Fold: [0.5171506303798025, 0.4168360746957386, 0.4748621017954998, 0.4937361530735427, 0.43840137317508165]
MSE Scores for Each Fold: [np.float64(12.35013639433459), np.float64(14.523151113585127), np.float64(16.696497260569775), np.float64(15.658833251772153), np.float64(16.545226845695264)]

Target: updrs_2
Average R2 Score: 0.5517
Average Mean Squared Error: 15.8925
R2 Scores for Each Fold: [0.6069459157653518, 0.5648825818147876, 0.5096606903098604, 0.5281525263679874, 0.5486208300231181]
MSE Scores for Each Fold: [np.float64(12.837666006507707), np.float64(12.932986847841905), np.float64(19.55580052689506), np.float64(18.859509900773283), np.float64(15.276595295715305)]

Target: updrs_3
Average R2 Score: 0.5904
Average Mean Squared Error: 95.5764
R2 Scores for Each Fold: [0.5986845128856773, 0.6383448273315435, 0.5413203718748335, 

Train, evaluate, save, and load a Multi-Output Random Forest Regressor to predict UPDRS scores.

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pickle  # For saving and loading models

# Load datasets with full file paths
files = [
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_0.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_6.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_12.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_24.csv'
]
dataframes = [pd.read_csv(file) for file in files]

# Combine datasets
data = pd.concat(dataframes, ignore_index=True)

# Define features (X) and targets (y)
X = data.iloc[:, 10:]  # Features starting from column 10
y = data[['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']]  # Targets

# Split data into training and testing sets for final model saving
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Multi-Output Random Forest Regressor
rf = RandomForestRegressor(random_state=42, n_estimators=100)
multi_output_rf = MultiOutputRegressor(rf)

# Train the final model on the training set
multi_output_rf.fit(X_train, y_train)

# Save the trained model and feature names to a file using pickle
model_filename = "random_forest_model_with_features.pkl"
with open(model_filename, 'wb') as file:
    pickle.dump((multi_output_rf, X_train.columns.tolist()), file)
print(f"Model and feature names saved to {model_filename}")

# Evaluate the model on the test set
y_pred = multi_output_rf.predict(X_test)
r2_scores = [r2_score(y_test[col], y_pred[:, i]) for i, col in enumerate(y.columns)]
mse_scores = [mean_squared_error(y_test[col], y_pred[:, i]) for i, col in enumerate(y.columns)]

print("\nEvaluation on Test Set:")
for i, col in enumerate(y.columns):
    print(f"Target: {col}")
    print(f"R2 Score: {r2_scores[i]:.4f}")
    print(f"Mean Squared Error: {mse_scores[i]:.4f}")

# Load the saved model and feature names for future predictions
with open(model_filename, 'rb') as file:
    loaded_model, feature_names = pickle.load(file)
print("\nLoaded the saved model and feature names successfully!")

# Make predictions on new data (example with test data)
# Ensure input features align with the feature names
aligned_test_data = X_test.reindex(columns=feature_names, fill_value=0)
new_predictions = loaded_model.predict(aligned_test_data)

print("\nPredictions on Test Data:")
print(new_predictions)


Model and feature names saved to random_forest_model_with_features.pkl

Evaluation on Test Set:
Target: updrs_1
R2 Score: 0.5254
Mean Squared Error: 12.1397
Target: updrs_2
R2 Score: 0.5975
Mean Squared Error: 13.1464
Target: updrs_3
R2 Score: 0.5906
Mean Squared Error: 89.4901
Target: updrs_4
R2 Score: 0.1898
Mean Squared Error: 3.6581

Loaded the saved model and feature names successfully!

Predictions on Test Data:
[[ 9.86333333  0.865       2.36333333  0.36583333]
 [ 8.63975     6.16416667 18.10633333  2.20209524]
 [ 4.8055      4.71066667 12.7375      0.49      ]
 ...
 [11.19833333 14.18455556 31.64066667  0.745     ]
 [ 9.4585     10.80566667 18.62766667  1.099     ]
 [ 5.45116667  2.65916667  4.66583333  1.075     ]]


Train and evaluate a Multi-Output Support Vector Regressor (SVR) to predict UPDRS scores using K-Fold Cross-Validation.

In [7]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import KFold
import numpy as np

# Load datasets with your file paths
files = [
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_0.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_6.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_12.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_24.csv'
]
dataframes = [pd.read_csv(file) for file in files]

# Combine datasets
data = pd.concat(dataframes, ignore_index=True)

# Define features (X) and targets (y)
X = data.iloc[:, 10:]  # Features starting from column 10 (already standardized)
y = data[['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']]  # Targets

# Initialize Multi-Output SVR
svm = SVR(kernel='rbf', C=1.0, epsilon=0.1)
multi_output_svm = MultiOutputRegressor(svm)

# Function to perform K-Fold Cross-Validation with separate metrics
def perform_kfold_cv_svm_separate(X, y, k):
    kf = KFold(n_splits=k, shuffle=True, random_state=42)
    results = {col: {"r2": [], "mse": []} for col in y.columns}  # Initialize results for each UPDRS target

    for train_index, test_index in kf.split(X):
        X_train_cv, X_test_cv = X.iloc[train_index], X.iloc[test_index]
        y_train_cv, y_test_cv = y.iloc[train_index], y.iloc[test_index]

        # Train the Multi-Output SVR model
        multi_output_svm.fit(X_train_cv, y_train_cv)
        y_pred_cv = multi_output_svm.predict(X_test_cv)

        # Calculate metrics for each target separately
        for i, col in enumerate(y.columns):
            r2 = r2_score(y_test_cv[col], y_pred_cv[:, i])
            mse = mean_squared_error(y_test_cv[col], y_pred_cv[:, i])
            results[col]["r2"].append(r2)
            results[col]["mse"].append(mse)

    # Print results for each target
    print(f"\nK-Fold Cross-Validation with {k} Folds (SVM):")
    for col in y.columns:
        print(f"\nTarget: {col}")
        print(f"Average R2 Score: {np.mean(results[col]['r2']):.4f}")
        print(f"Average Mean Squared Error: {np.mean(results[col]['mse']):.4f}")
        print(f"R2 Scores for Each Fold: {results[col]['r2']}")
        print(f"MSE Scores for Each Fold: {results[col]['mse']}")

# Perform 5-Fold Cross-Validation
perform_kfold_cv_svm_separate(X, y, k=5)

# Perform 10-Fold Cross-Validation
perform_kfold_cv_svm_separate(X, y, k=10)



K-Fold Cross-Validation with 5 Folds (SVM):

Target: updrs_1
Average R2 Score: 0.2227
Average Mean Squared Error: 22.2073
R2 Scores for Each Fold: [0.21062765134261763, 0.25422306557891683, 0.21160459432845258, 0.2120807404137368, 0.2248654690880869]
MSE Scores for Each Fold: [np.float64(20.19026384875106), np.float64(18.5728757312494), np.float64(25.06663826025113), np.float64(24.370486608168452), np.float64(22.836196595379835)]

Target: updrs_2
Average R2 Score: 0.2444
Average Mean Squared Error: 26.7499
R2 Scores for Each Fold: [0.25445256589250254, 0.29547768759315496, 0.19731113346903328, 0.2130994687956521, 0.2615159577706051]
MSE Scores for Each Fold: [np.float64(24.350564807684457), np.float64(20.940503458518066), np.float64(32.0129817227149), np.float64(31.4520246234191), np.float64(24.99344807174021)]

Target: updrs_3
Average R2 Score: 0.1826
Average Mean Squared Error: 190.1347
R2 Scores for Each Fold: [0.1641062841193821, 0.22114141857091618, 0.1340743276744828, 0.17104206

Train, evaluate, save, and load a Multi-Output Support Vector Regressor (SVR) to predict UPDRS scores.

In [6]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import pickle  # For saving and loading models
import numpy as np

# Load datasets with your file paths
files = [
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_0.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_6.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_12.csv',
    r'C:\Users\sarah\Desktop\saragp\dataset_cleaned\t_plus_24.csv'
]
dataframes = [pd.read_csv(file) for file in files]

# Combine datasets
data = pd.concat(dataframes, ignore_index=True)

# Define features (X) and targets (y)
X = data.iloc[:, 10:]  # Features starting from column 10
y = data[['updrs_1', 'updrs_2', 'updrs_3', 'updrs_4']]  # Targets

# Split data into training and testing sets for final model saving
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Multi-Output SVR
svm = SVR(kernel='rbf', C=1.0, epsilon=0.1)
multi_output_svm = MultiOutputRegressor(svm)

# Train the final model on the training set
multi_output_svm.fit(X_train, y_train)

# Save the trained model and feature names to a file using pickle
model_filename = "svr_model_with_features.pkl"
with open(model_filename, 'wb') as file:
    pickle.dump((multi_output_svm, X_train.columns.tolist()), file)
print(f"Model and feature names saved to {model_filename}")

# Evaluate the model on the test set
y_pred = multi_output_svm.predict(X_test)
r2_scores = [r2_score(y_test[col], y_pred[:, i]) for i, col in enumerate(y.columns)]
mse_scores = [mean_squared_error(y_test[col], y_pred[:, i]) for i, col in enumerate(y.columns)]

print("\nEvaluation on Test Set:")
for i, col in enumerate(y.columns):
    print(f"Target: {col}")
    print(f"R2 Score: {r2_scores[i]:.4f}")
    print(f"Mean Squared Error: {mse_scores[i]:.4f}")

# Load the saved model and feature names for future predictions
with open(model_filename, 'rb') as file:
    loaded_model, feature_names = pickle.load(file)
print("\nLoaded the saved model and feature names successfully!")

# Make predictions on new data (example with test data)
# Ensure input features align with the feature names
aligned_test_data = X_test.reindex(columns=feature_names, fill_value=0)
new_predictions = loaded_model.predict(aligned_test_data)

print("\nPredictions on Test Data:")
print(new_predictions)


Model and feature names saved to svr_model_with_features.pkl

Evaluation on Test Set:
Target: updrs_1
R2 Score: 0.2106
Mean Squared Error: 20.1904
Target: updrs_2
R2 Score: 0.2545
Mean Squared Error: 24.3506
Target: updrs_3
R2 Score: 0.1641
Mean Squared Error: 182.7280
Target: updrs_4
R2 Score: 0.1210
Mean Squared Error: 3.9684

Loaded the saved model and feature names successfully!

Predictions on Test Data:
[[ 8.11089806  2.2599384  13.896859    0.10004165]
 [ 7.2321145   5.47756637 16.2996368   0.52621942]
 [ 3.16471844  2.85824504 10.28036243 -0.03172578]
 ...
 [ 6.96502299  6.61728163 19.37957809  0.19223405]
 [ 8.899965    5.95430956 15.94035091  0.85568912]
 [ 5.39977652  3.88654954 13.66413583  0.0998816 ]]
